"""Add column created_at to faceembeddings model

Revision ID: ac70ec5156fa
Revises: 58b9fa368d3d
Create Date: 2025-08-05 11:33:27.716719

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ac70ec5156fa'
down_revision = '58b9fa368d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faceembeddings', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.drop_index('faceembeddings_embedding_idx', table_name='faceembeddings', postgresql_using='hnsw')
    op.drop_index('faceembeddings_embedding_idx1', table_name='faceembeddings', postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('faceembeddings_embedding_idx1', 'faceembeddings', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index('faceembeddings_embedding_idx', 'faceembeddings', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_column('faceembeddings', 'created_at')
    # ### end Alembic commands ###
